server.port=8085
enc.key=X9mKp2vQrLzN4wB8cFtV6sDhJ1yR3aE7
spring.application.name=biz-ttd-admin-srv
mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
logging.config=classpath:logback-spring.xml
logging.level.org.springframework.web.servlet.handler=DEBUG
#  file:
#     path: ./logs
#   name: ./logs/biz-ttd-srv.log
# ==================== SpringDoc OpenAPI ====================
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=list
springdoc.swagger-ui.default-model-expand-depth=1
springdoc.swagger-ui.default-models-expand-depth=1
springdoc.default-flat-param-object=true
springdoc.show-actuator=false
springdoc.writer-with-default-pretty-printer=true
nacos.rpc.enabled=true
# Nacos ????
nacos.rpc.server-addr=127.0.0.1:8848
nacos.rpc.namespace=dev
nacos.rpc.group=DEFAULT_GROUP
# RPC ????????
nacos.rpc.server-host=0.0.0.0
nacos.rpc.server-port=19090
# ????
nacos.rpc.env=dev
# Undertow ????
nacos.rpc.io-threads=4
nacos.rpc.worker-threads=32
nacos.rpc.direct-buffers=true
# OkHttp ??????????
nacos.rpc.connect-timeout=5000
nacos.rpc.read-timeout=10000
nacos.rpc.write-timeout=10000
ttd.nacos.namespace=dev
ttd.nacos.server-addr=127.0.0.1:8848
ttd.nacos[0].namespace=dev
ttd.nacos[0].group=biz-feature-admin-srv
ttd.nacos[0].dataId=application.properties




